[package]
name = "suika_templates"
version = "0.1.0"
edition = "2021"
authors = ["Jon Watkins"]
repository = "https://github.com/JonWatkins/suika/tree/master/crates/suika_templates"
license = "MIT"
readme = "README.md"

[lib]
name = "suika_templates"
path = "src/lib.rs"
