[package]
name = "suika_http"
version = "0.1.0"
edition = "2021"
authors = ["Jon Watkins"]
publish = false

[dependencies]
suika_utils = { path = "../suika_utils" }
suika_errors = { path = "../suika_errors" }
suika_mime = { path = "../suika_mime" }
suika_json = { path = "../suika_json" }
